djiangodeprueba/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
import djiangodeprueba

urlpatterns = [
    path('', cargar_pagina_inicio),
    path('prueba/', registroDatos)
]

pruebadjiango/urls.py
from django.contrib import admin
from django.urls import path, include

import djiangodeprueba

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djiangodeprueba/',include('djiangodeprueba.urls')),
]

djiangodeprueba/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class tipoprueba(models.TextChoices):
    MALA = "Mala"
    NORMAL = "Normal"

# Create your models here.
class prueba(models.Model):
    nombre = models.CharField(max_length=150)
    apellidos = models.CharField(max_length=150)
    tipo = models.CharField(max_length=30,choices=tipoprueba.choices)
    numero = models.IntegerField()
    fecha_salida = models.DateTimeField()

    def __str__(self):
        return self.nombre

class pruebita(models.Model):
    amount = models.FloatField()
    prueba = models.ForeignKey(prueba, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.amount) + "y el nombre de la prueba"

class prueba_del_algodon(models.Model):
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class UsuarioManager(BaseUserManager):
    def create_user(self,email, password, **extra_fields):
        if not email:
            raise ValueError("El usuario debe tener un email válido")
        user = self.model(email=self.normalize_email(email),**extra_fields )
        user.set_password(password)
        user.save(using = self.db)
        return user

    def create_superuser(self,email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault("is_susperuser", True)
        return self.create_user(email,password,**extra_fields)



class Usuario(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(unique=True, max_length=255, blank=False)
    password = models.CharField(max_length=255, blank=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD= 'username'
    REQUIRED_FIELDS = ['username,password']

    objects = UsuarioManager()

    def __str__(self):
        return self.username, self.email

djiangodeprueba/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class UsuarioCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=255, required=True, help_text='Requerido. Ingrese una dirección de correo electrónico válida.')
    username = forms.CharField(max_length=255, required=True, help_text='Requerido. 255 caracteres o menos. Solo letras, números y @/./+/-/_ caracteres.')
    password1 = forms.CharField(max_length=255, required=True, help_text='Requerido. 255 caracteres o menos. Al menos 8 caracteres y no pueden ser todos números.')
    password2 = forms.CharField(max_length=255, required=True, help_text='Requerido. Ingrese la misma contraseña que antes, para verificarla.')

    class Meta:
        model = Usuario
        fields = ('email', 'username', 'password1', 'password2')

djiangodeprueba/views.py
from django.shortcuts import render, redirect
from .models import *
from .añadir_datos import *
# Create your views here.
def cargar_pagina_inicio(request):

    return render(request,'inicio.html')

def registroDatos(request):
    lista_datos = prueba.objects.all()
    lista_datos2 = prueba_del_algodon.objects.all()

    if request.method == "GET":

        return render(request,'ListaPrueba.html',{'prueba': lista_datos,"prueba_algodon":lista_datos2})
    else :
        nuevo_user = Usuario()
        nuevo_user.username = request.POST.get("name")
        nuevo_user.password = request.POST.get("pass")
        Usuario.save(nuevo_user)
        return redirect('/djiangodeprueba/prueba')

templates/ListaPrueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ListaPrueba</title>
</head>
<body>
    <header>
        <div class="lista"><li><a href="/djiangodeprueba">Inicio</a></li><li><a href="/djiangodeprueba/prueba">Prueba</a></li><li></li> </div>
    </header>
    <div class="fu" >
        <form  method="POST">
        {% csrf_token %}
        <input id="name" name="name" type="text" value="">
    <input id="pass" name="pass" type="text" value="">
            <button type="submit" >ok</button>
    </form></div>
    {% for pr in prueba %}
        <h2>{{ pr.nombre }}</h2>
        <h2>{{ pr.apellidos }}</h2>
        {% for prt in pr.pruebita_set.all %}
         <h3>{{ prt.amount }}</h3>
        {% endfor %}
    {% endfor %}
    {% for al in prueba_algodon %}
        <h2>{{ al.nombre }}</h2>
    {% endfor %}
    
</body>
</html>

templates/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Prueba</title>
    <!--<link rel="stylesheet" href="header.css">-->
    <style>
        header{
display: flex;
flex-direction: row;
            border-bottom: 1px solid black;
            height: 150px;
            align-items: end;

}
.lista{display: flex;
    flex-direction: row;
    color: black;
    font-weight: bold;
    font-size: large;
}
.lista>a{
background-color: #3a99ff;
    margin:10px 30px 10px 30px;
    width: 70px;
    height: 40px;
    padding-top: 15px;
    padding-left: 10px;
    text-decoration: none;
    color:black;
    border: 1px solid black;
    border-radius: 10px;
}
    </style>
</head>
<body>

    <header>
        <div class="lista"><a href="/djiangodeprueba">Inicio</a><a href="/djiangodeprueba/prueba">Prueba</a> </div>
    </header>
    <h1>Biienvenido a jumanji</h1>
</body>
</html>